#!/usr/bin/env python

from setuptools import setup

setup(name='Emojipedia',
      packages=['emojipedia'],
      version='0.4.0',
      description='Emoji data from Emojipedia',
      author='Benjamin Congdon',
      author_email='bcongdo2@illinois.edu',
      license='MIT',
      url='https://github.com/benjamincongdon',
      keywords=['emoji', 'emojipedia'],
      install_requires=['appdirs==1.4.0',
                        'beautifulsoup4==4.4.0',
                        'codeclimate-test-reporter==0.2.0',
                        'coverage==4.3.4',
                        'flaky==3.4.0',
                        'nose==1.3.7',
                        'packaging==16.8',
                        'pyparsing==2.1.10',
                        'requests==2.5.0',
                        'six==1.10.0'],
      classifiers=['Programming Language :: Python :: 2',
                   'Programming Language :: Python :: 2.6',
                   'Programming Language :: Python :: 2.7',
                   'Programming Language :: Python :: 3',
                   'Programming Language :: Python :: 3.5',
                   'Programming Language :: Python :: 3.6',
                   'Topic :: Communications :: Chat',
                   'Topic :: Text Processing',
                   'Topic :: Utilities'],
      )
